In [212]:
import networkx as nx
import numpy as np
import scipy

In [177]:
def g_ER(K,p): #an ars is included with probability p independently of any other arc
    G_p = nx.erdos_renyi_graph(K, p)
    return(G_p)
def g_r(K,r): # K>r>=3 AND Kr is EVEN
    G_r = nx.random_regular_graph(r,K)  
    return(G_r)

In [213]:
def connectivity_irreducible(A):
    #A= nx.adjacency_matrix(G).toarray()
    n=A.shape[0]
    sum_matrix=np.add(np.eye(n),A)
    temp_power_A=A
    for i in range(1,n-1):
        temp_power_A=np.matmul(temp_power_A,A)
        sum_matrix=np.add(sum_matrix,temp_power_A)
    print(sum_matrix)
    eigvals = scipy.linalg.eigvals(sum_matrix)
    print(eigvals,'\n')
    if np.all(eigvals > 0):
        return(1)
    else:
        return(0)

In [234]:
def Connectivity_irreducible(A):
    #A= nx.adjacency_matrix(G).toarray()
    n=A.shape[0]
    sum_matrix=np.linalg.matrix_power(np.add(np.eye(n),A),n-1)
    
    eigvals = np.linalg.eigvals(sum_matrix)
    print(eigvals,'\n')
    if np.all(eigvals > 0):
        return(1)
    else:
        return(0)

In [230]:
G=nx.erdos_renyi_graph(10, 0.8)
Ar=nx.adjacency_matrix(G).toarray()

C:\Users\Michele\AppData\Local\Temp\ipykernel_26640\573968294.py:2: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  Ar=nx.adjacency_matrix(G).toarray()


In [233]:
nx.is_connected(G)

True

In [231]:
Connectivity_irreducible(Ar)

[ 6.89105823e+07  4.22576271e+03 -2.79875902e+02  1.44630062e+02
 -7.80148460e+00 -5.40169690e-02  4.02299226e-02  4.49329986e-03
 -1.44839055e-09  1.00000000e+00] 



0

In [224]:
Ar


array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0]], dtype=int32)

In [221]:
connectivity_irreducible(Ar)

[[1. 0. 0. 0.]
 [0. 2. 0. 2.]
 [0. 0. 1. 0.]
 [0. 2. 0. 2.]]
[4.0000000e+00+0.j 4.4408921e-16+0.j 1.0000000e+00+0.j 1.0000000e+00+0.j] 



1